### ISSUE TITLE
All the recipes are not there

### ISSUE THREAD

**Issue by adam-drewery** [RobBollons/recipes#1]
I look in the repo and there are zero recipes. This could be improved by adding recipes.

**Comment by mrbalihai** [comment]
This is resolved now, I've added a recipe for focaccia bread.

**Comment by adam-drewery** [comment]
This is great, however a man cannot sustain himself on bread alone. More recipes are required for a healthy balanced diet.

**Comment by mrbalihai** [comment]
It's damn good focaccia though, could sustain you for a long time
